version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: 'postgres://hello:django@data:5432/yashoes'
      CACHE_URL: 'redis://cache:6379/'
      STORAGE_URL: 'storage:9000'
    links:
      - data:data
      - cache:cache
      - storage:storage
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]

  data:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'yashoes'
      POSTGRES_USER: 'hello'
      POSTGRES_PASSWORD: 'django'
    restart: always
    volumes:
      - ./.tmp/data:/var/lib/postgresql/data

  cache:
    image: redis:5.0.3-alpine
    ports:
      - 6379:6379
    restart: always
  storage:
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EDAMPLP
      MINIO_SECRET_KEY: wJalrXUtnFEMKJH7MDENJFTPxRfiCYEXAMPLEKEY
    command: 
      server /export
    restart: always

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    volumes:
      - .:/code
    expose:
      - 5555
    ports:
      - 5555:5555
    tty: true
    environment:
      DATABASE_URL: 'postgres://hello:django@data:5432/yashoes'
      CACHE_URL: 'redis://cache:6379/'
      STORAGE_URL: 'storage:9000'
    links:
      - data:data
      - cache:cache
      - storage:storage
    command: celery flower -A myproject
