# Generated by Django 2.1.5 on 2019-01-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yashoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_notification_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='comments',
            field=models.ManyToManyField(to='yashoes.Comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='transactions',
            field=models.ManyToManyField(to='yashoes.Transaction'),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='user_version',
        ),
    ]
