# Generated by Django 2.1.5 on 2019-01-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yashoes', '0003_add_related_name_for_product_and_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yashoes.Comment'),
        ),
    ]
