# Generated by Django 2.1.5 on 2019-01-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yashoes', '0003_auto_20190118_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[(1, 'in processing'), (2, 'in delivery'), (3, 'done'), (4, 'cancel')], max_length=1),
        ),
    ]
