# Generated by Django 2.1.5 on 2019-01-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yashoes', '0003_auto_20190118_0717'),
        ('yashoes', '0003_auto_20190118_0458'),
    ]

    operations = [
    ]
