# Generated by Django 2.1.5 on 2019-01-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yashoes', '0004_merge_20190118_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[(1, 'in processing'), (2, 'in delivery'), (3, 'done'), (4, 'cancel')], max_length=1),
        ),
    ]
