# Generated by Django 2.1.5 on 2019-01-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yashoes', '0004_merge_20190118_0814'),
        ('yashoes', '0004_auto_20190118_1024'),
    ]

    operations = [
    ]
