# Generated by Django 2.1.5 on 2019-01-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yashoes', '0006_auto_20190123_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('1', 'in processing'), ('2', 'in delivery'), ('3', 'done'), ('4', 'cancel')], max_length=1),
        ),
    ]
