# Generated by Django 2.1.5 on 2019-01-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yashoes', '0008_auto_20190128_0439'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'product')},
        ),
    ]
