# Generated by Django 2.1.5 on 2019-01-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yashoes', '0009_auto_20190128_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionvariant',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
